[package]
name = "mab"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "mab"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
mab-core.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
